server.port=8080

# ===============================
# H2 DATABASE (FILE MODE)
# ===============================
spring.datasource.url=jdbc:h2:file:./data/perfulandia_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# JWT
# ===============================
jwt.secret=VW5hQ2xhdmVNdXlTZWNyZXRh
jwt.expiration=86400000
